development:
  adapter: postgresql
  encoding: unicode
  database: active_development
  pool: 5
  username: dchuang
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: active_test
  pool: 5
  username: dchuang
  password: 